Redocly/redoc

docker-compose.yml

`node` `7`                `8 days ago`          `666 MB`
`node` `7-alpine`    `8 days ago`          `59.1 MB`

Lets use a small docker image (600MB Savings ZOMG)

---

demo/examples/multiple-apis/index.html

Spacing applied to aaaaalll li's

---

lib/components/Redoc/redoc-initial-styles.scss

Just noticed there were two HTTP requests when we can do it one :)

Make a single request for Google Fonts

---

cli/index.ts
cli/package.json
cli/yarn.lock

Create directories when a path is specified in the --output option

---

cli/index.ts

Return 1 as exit code if an error happens in the cli

---

cli/index.ts

Run Yargs in strict mode and return exit code 1 if the command is invalid

---

src/components/Fields/FieldDetails.tsx

Simplify the template by using html escape chars

Use HTM escape chars

---

src/types/open-api.d.ts

Adding typing for this Redoc-specific property.

Add x-code-samples to TS types

---

cli/index.ts

Watch the directory that contains the specified spec instead of the spec itself

---

src/services/models/Schema.ts

Bugfix that enables rendering additionalProperties set to true.

---

lib/utils/spec-manager.ts

set default protocol and host

---

README.md
src/components/Fields/Extensions.tsx
src/components/Fields/FieldDetails.tsx
src/components/Operation/Operation.tsx
src/services/RedocNormalizedOptions.ts
src/services/models/Field.ts
src/services/models/Operation.ts
src/services/models/Schema.ts
src/utils/openapi.ts

add the option to render vendor extensions

---

cli/package.json
cli/yarn.lock

Fixes issue https://github.com/Rebilly/ReDoc/issues/698

Fix old peer dependency issue with styled-components in cli

---

cli/index.ts
cli/package.json
cli/yarn.lock

Caveat: could not get this to work with a debounce.
Fixes: recursive file watching on Linux (and thus Docker).

refactor(cli): Use chokidar for watching

---

README.md

Changing the link was likely forgotten in 07b5e62897bd25683c21de7aab768990f8619837

fix link to Dockerfile.

---

src/components/SecuritySchemes/SecuritySchemes.tsx
src/utils/__tests__/helpers.test.ts
src/utils/helpers.ts

fix: update apiKey in to be titleize

---

README.md

Makes it kind of hard to do a copy/paste 😅

Fixed small typo in Readme

---

src/common-elements/tabs.ts

fix: styled-component style error in tabs

---

README.md
docs/redoc-vendor-extensions.md
src/services/models/Schema.ts
src/utils/openapi.ts

Supply custom name to be displayed for property name of `additionalProperties`.

Add x-additionalPropertiesName (#622)

---

README.md
src/components/Redoc/Redoc.tsx
src/components/SideMenu/SideMenu.tsx
src/services/RedocNormalizedOptions.ts

Fold and expand menu items by clicking

update: fold active MenuItem if clicked

---

.github/CONTRIBUTING.md

I hereby confirm that I have read the contribution guide till the very last line

docs: fix typo

---

src/utils/jsonToHtml.ts

wrap json examples in code tag

---

src/services/models/Operation.ts
src/services/models/Schema.ts
src/utils/__tests__/openapi.test.ts
src/utils/openapi.ts

The method of sortByRequired has a bug, see #1104, #1121

fix: Fixed  method sortByRequired

---

src/services/RedocNormalizedOptions.ts

fix: fix passing boolean value to showExtensions options

---

demo/playground/hmr-playground.tsx
src/components/Fields/EnumValues.tsx
src/services/RedocNormalizedOptions.ts

feat: add maxDisplayedEnumValues config and buttons for show/hide enums

---

src/components/Callbacks/CallbackTitle.tsx
src/components/Callbacks/styled.elements.ts

fix: make callbacks expandable by keyboard

---

src/components/Responses/ResponseTitle.tsx
src/components/Responses/styled.elements.ts

fix: display response code at the top after adding a line break

---

src/common-elements/fields.ts
src/components/Fields/FieldDetails.tsx

fix: show long pattern and add toggle button

---

src/components/JsonViewer/JsonViewer.tsx
src/components/JsonViewer/style.ts
src/utils/jsonToHtml.ts

fix: make samples accessible by keyboard

---

README.md

Add 'maxDisplayedEnumValues' option to docs

---

cli/index.ts

chore: remove duplicate semicolons

---

src/components/SearchBox/styled.elements.tsx

Fixes https://github.com/Redocly/redoc/issues/1502

fix: background-color in search results

---

cli/index.ts

Add disableGoogleFont parameter to serve command

---

src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap
src/utils/__tests__/loadAndBundleSpec.test.ts

Added unit tests to check proper loading and bundling API definitions using **openapi-core** after migration from **json-schema-ref-parser**.
Kudos to @Marshevskyy

chore: unit tests to check loading and bundling api definitions with openapi-core

---

README.md

docs: update specUrl

---

cli/package.json

chore: update(cli) engine node version >=12

---

.github/pull_request_template.md

chore: added pull request template

---

package-lock.json
package.json
src/utils/highlight.ts

Add yaml highlight via prism
fixes https://github.com/Redocly/redoc/issues/1669

feat: add yaml highlight

---

cli/package.json

This PR fixes the following security issue:
`Regular Expression Denial of Service - https://npmjs.com/advisories/1762`
https://github.com/Redocly/redoc/issues/1676

Fix: redoc-cli security issue

---

README.md

Looking at BoxKnight's API docs revealed that it is powered by ReDoc. 
Hence I thought it might be a good idea to add it to the existing _Some Real-life usages_ section.

[Docs] Add real-life usage example: BoxKnight

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Add GitHub template for bug reports and feature requests.

chore: add github template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add headers to GitHub template for

chore: add headers to github templates

---

package-lock.json
package.json

chore: up version for release

---

package-lock.json
package.json

- update redocly/openapi-core to last version.
- fixes https://github.com/Redocly/redoc/issues/1687

chore: update libs

---

config/docker/index.tpl.html

fixed https://github.com/Redocly/redoc/issues/1758

fix: mobile view in docker image

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.58

---

cli/npm-shrinkwrap.json
cli/package.json

chore(cli): v0.13.1

---

package-lock.json
package.json

[size-limit](https://www.npmjs.com/package/size-limit) is a more modern replacement for [bundlesize](https://www.npmjs.com/package/bundlesize).
In addition, bundlesize uses binary dependencies that are not required on modern Nodes.
None of these really apply, so checking all of them. ✅

Replace bundlesize with size-limit

---

demo/webpack.config.ts
package-lock.json
package.json

chore: update packages

---

src/services/MarkdownRenderer.ts

See https://github.com/Redocly/redoc/pull/1841
also fix an additional bug.

fix: attachHeadingsDescriptions match headings incorrectly

---

src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap

chore: update snapshots

---

src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap
src/utils/__tests__/openapi.test.ts
src/utils/openapi.ts

fix: definition name util

---

src/components/Parameters/Parameters.tsx

fix: writeOnly params displaying in webhook

fix: writeOnly params displaying in webhook

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.60

---

cli/npm-shrinkwrap.json
cli/package.json

chore(cli): v0.13.2

---

cli/npm-shrinkwrap.json
cli/package.json

chore: v0.13.4

---

.gitignore
package.json

chore: add cache option for eslint

chore: add cache option for eslint

---

package-lock.json
package.json

hotfix: field expand

---

package-lock.json
package.json

Revert "hotfix: field expand"

---

package-lock.json
package.json

chore: 2.0.0-rc.62

---

CHANGELOG.md
cli/npm-shrinkwrap.json
cli/package.json

chore: (cli) v0.13.6

---

cli/npm-shrinkwrap.json
demo/webpack.config.ts
package-lock.json
package.json
src/common-elements/perfect-scrollbar.tsx
webpack.config.ts

fixes https://github.com/Redocly/redoc/issues/1883
l)

fix: scroll in sidebar

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.63

---

cli/npm-shrinkwrap.json
cli/package.json

chore: cli-v0.13.17

---

README.md

add showObjectSchemaExamples to readme

chore: add showObjectSchemaExamples to readme

---

package-lock.json
package.json

bump json-pointer version to avoid CVE-2021-23820

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.64

---

cli/npm-shrinkwrap.json
cli/package.json

chore: cli-v0.13.8

---

package-lock.json
package.json

update prismjs lib to version 1.27.0

chore: update prismjs lib

---

cli/npm-shrinkwrap.json
cli/package.json
package-lock.json
package.json

update `cli` libs for future `redoc-cli` fixes.

chore: update openapi-core and yargs libs

---

src/common-elements/headers.ts

H2: Set color form theme.colors.primary.main so that it can be customized.

H2: Set color form theme.colors.primary.main

---

src/components/SideMenu/SideMenu.tsx

Use "Documentation Powered by Redocly" instead of "... by ReDoc" and updated link to the Redoc OSS vs Redocly API Reference.

chore: change side menu message

---

cli/README.md
cli/npm-shrinkwrap.json
cli/package.json

chore:cli-v0.13.10

---

src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap

update snapshot after [PR](https://github.com/Redocly/redoc/pull/1600) changes

fix: update snapshot

---

CHANGELOG.md
package-lock.json
package.json

chore:v2.0.0-rc.67

---

src/components/SecuritySchemes/SecuritySchemes.tsx

fixes https://github.com/Redocly/redoc/issues/1968

fix: not show scopes if keys empty or not exist

---

src/common-elements/fields.ts
src/components/Fields/Examples.tsx

fix: large text in examples value

---

demo/openapi-3-1.yaml
src/services/__tests__/fixtures/3.1/unevaluatedProperties.json
src/services/__tests__/models/Schema.test.ts
src/services/models/Schema.ts
src/types/open-api.ts
src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap
src/utils/__tests__/openapi.test.ts
src/utils/openapi.ts

feat: Support OAS 3.1 unevaluatedProperties

---

.github/workflows/publish.yml

publish dockerhub and add platforms
close #1966

chore: publish dockerhub

---

CHANGELOG.md
package-lock.json
package.json

chore:v2.0.0-rc.68

---

config/docker/Dockerfile

chore: fix dockerhub publish

---

.github/workflows/main.yml
.github/workflows/publish.yml
config/docker/Dockerfile

chore: fix publish dockerhub

---

cli/npm-shrinkwrap.json
cli/package.json

chore:cli-v0.13.12

---

package-lock.json
package.json

upgrade openapi-core to v1.0.0-beta.97

chore: upgrade openapi-core to 1.0.0-beta.97

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.69

---

cli/npm-shrinkwrap.json
cli/package.json

chore: cli-v0.13.13

---

config/docker/Dockerfile

add node version to docker file for fix publish to dockerhub

fix: add node version to docker

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.70

---

scripts/publish-cdn.sh

fix `publish-cdn` script related to [CI/CD actions](https://github.com/Redocly/redoc/runs/6670958627?check_suite_focus=true)

chore: fix publish-cdn script

---

demo/openapi-3-1.yaml
src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap
src/services/OpenAPIParser.ts
src/services/__tests__/models/__snapshots__/Schema.test.ts.snap
src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap

we lost sibling functionality in version 2.0.0-rc.57-58. This PR fix it.
fix https://github.com/Redocly/redoc/issues/2042

fix: merge reference for openapi 3.1

---

package.json

add checking bundle size for web and lib bundle
remove unused dependency url-polifill

chore: improve bundle size and remove url-polifill

---

src/services/__tests__/fixtures/3.1/patternProperties.json
src/services/__tests__/models/Schema.test.ts
src/services/models/Schema.ts
src/utils/openapi.ts

fixes https://github.com/Redocly/redoc/issues/2071

fix: nested patternProperties

---

cli/index.ts
package-lock.json
package.json
src/common-elements/CopyButtonWrapper.tsx
src/common-elements/shelfs.tsx
src/components/Callbacks/CallbackTitle.tsx
src/components/DropdownOrLabel/DropdownOrLabel.tsx
src/components/ErrorBoundary.tsx
src/components/JsonViewer/JsonViewer.tsx
src/components/Markdown/AdvancedMarkdown.tsx

fixes: https://github.com/Redocly/redoc/issues/2061
fixes: https://github.com/Redocly/redoc/issues/1820
This PR related to https://github.com/Redocly/redoc/issues/1820#issuecomment-1166599837. 
update webpack for fix bug in `loader-runner` (throw new Error("callback(): The callback was already called.");)
update openapi-core to v1.0.0-beta.104
step to reproduce:
- versions:
nodejs: v18.4.0
yarn 1.22.19
- steps:
yarn install
yarn run build:demo

chore: fix yarn webpack 5

---

src/components/Endpoint/Endpoint.tsx
src/utils/helpers.ts
src/utils/openapi.ts

This reverts commit 98eec19647b63f3598ec30fdeb428f614cf93ad4.
We already have fix about that https://github.com/Redocly/redoc/pull/2081

chore: revert "fix: operation url in static page (#2093)"

---

cli/index.ts

related to https://github.com/Redocly/redoc/issues/2076

chore: use latest tag for build command

---

src/services/OpenAPIParser.ts
src/services/__tests__/fixtures/3.1/prefixItems.json
src/services/__tests__/fixtures/arrayItems.json
src/services/__tests__/models/Schema.test.ts
src/services/models/Schema.ts

fixes: https://github.com/Redocly/redoc/issues/2086

fix: recursion for boolean items

---

src/components/SideMenu/SideMenu.tsx
src/components/SideMenu/styled.elements.ts

fix: add label API docs by Redocly

---

CHANGELOG.md
package-lock.json
package.json

chore: v.2.0.0-rc.73

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.74

---

.github/workflows/main.yml
.github/workflows/publish.yml

fix publishing docker to GitHub packages
https://github.com/Redocly/redoc/runs/7562208992?check_suite_focus=true

fix: publishing docker image to github packages

---

.github/workflows/e2e-tests.yml
.github/workflows/publish.yml
cli/index.ts
cli/npm-shrinkwrap.json
cli/package.json

add notification to `redoc-cli` about the new version is available.

feat: add notification about available new version

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.75

---

.github/workflows/publish.yml

chore: fix integratin test in publish script

---

cli/npm-shrinkwrap.json
cli/package.json

chore: cli-v0.13.18

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.76

---

.github/workflows/publish.yml

fix https://github.com/Redocly/redoc/actions/runs/2883068464

fix: invalidate cache action

---

cli/npm-shrinkwrap.json
cli/package.json

chore: cli-v0.13.19

---

.github/workflows/main.yml

Fixed [this issue](https://github.com/Redocly/redoc/pull/2087)

fix latest docker cli tag

---

CHANGELOG.md
package-lock.json
package.json

chore: v2.0.0-rc.77

---

cli/npm-shrinkwrap.json

chore: reinstall cli with new npm

---

src/components/RedocStandalone.tsx

fixes: https://github.com/Redocly/redoc/issues/2174

fix: error with immutable object spec

---

README.md
demo/openapi-3-1.yaml
demo/openapi.yaml
src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap

- update link to redocly.com domain
- add global security to definition

chore: update link to redocly.com and add security to definition

---

src/components/Fields/FieldDetails.tsx

fixes https://github.com/Redocly/redoc/issues/1806

fix: default value for array query parameter

---

cli/npm-shrinkwrap.json
cli/package.json
package-lock.json

Fixes #2237
remove is_array package

remove isarray

---

demo/index.tsx

Fix the CORS proxy URL to resolve https://github.com/Redocly/redoc/issues/2009#issuecomment-1334750273.
I'm new to this project, so please let me know if I'm doing something wrong.

fix(demo): Get CORS proxy to work in Chrome on Windows

---

src/types/open-api.ts

fix(types/open-api): import type

---

cli/npm-shrinkwrap.json
cli/package.json

chore: cli-v0.13.21

---

package-lock.json
package.json
src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap

fixes https://github.com/Redocly/redoc/issues/2258

chore: update openapi-sampler

---

src/components/SideMenu/MenuItem.tsx

feat: enable keyboard navigation

---

docs/config.md

docs: fix admonition on config page

---

package-lock.json
package.json

upgrade `openapi-sampler` to latest version

chore: upgrade openapi-sampler

---

package-lock.json
package.json

chore: fix docker publish

---

package-lock.json
package.json

Some dev deps had known vulnerabilities.

chore: upgrade vulnerable dev dependencies

---

package-lock.json
package.json

Remove heavy bundlesize dependency which has vulnerabilities in child deps.

chore: remove heavy bundlesize dev dependency

---

docs/deployment/intro.md

Fix a code sample from some user feedback.
(internal link) https://app.cloud.redocly.com/org/redocly/project/marketing-site/feedback/fb_01j4y0brs7rszvmppqxz5vqd40
Install `http-server` and check how to run it; fix code snippet.

docs: fix http-server example from in-page feedback

---

config/docker/Dockerfile

upgrade node version for docker image
fix https://github.com/Redocly/redoc/issues/2481

chore: upgrade node version for docker

---

config/docker/Dockerfile

issue with docker build when installing esbuild https://github.com/Redocly/redoc/actions/runs/11362992735/job/31605979487. That PR should fix it.
https://github.com/evanw/esbuild/issues/3813

fix: docker build for publish

---

package-lock.json
package.json

updated webpack version

---

package-lock.json
src/components/StoreBuilder.ts

fix vulnerabilities for Redoc CE

chore: fix vulnerabilities

---

src/components/JsonViewer/JsonViewer.tsx
src/components/__tests__/JsonViewer.tsx

Fix #2619
_null_
Tested manually and unit test
_loom might make more sense if necessary_

feat: add keyboard navigation support to JsonViewer component

---

src/components/SideMenu/MenuItem.tsx

Fix #2621
_null_
- tested manually and locally.
- unit test not included due to the component need a lot of code to write to jsut write test for this one function, can be added as additional task.
_loom with keyboard stroke visualizer might makes more sense_

fix: enhance accessibility for menu items with keyboard support
