- lib/utils/SpecManager.ts
- tests/unit/SpecManager.spec.ts
Small update to fix fallback of host.
If `schema.host` is undefined then use host serving spec document, if one exists. [ref](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema)
Also fixed up an issue with scheme fallback where url parser returns a protocol with `:` at the end causing an invalid url
> Use api host if schema host is undefined

- lib/utils/pipes.ts
typescript was complaining about these lines
`
Argument of type 'String' is not assignable to parameter of type 'string'.
'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.
`
telling it that these were strings made it happy
> give type "string" for pipe transforms

- demo/swagger.yaml
- lib/components/JsonSchema/_json-schema-common.scss
- lib/components/JsonSchema/json-schema.html
- lib/services/schema-helper.service.ts
Closes #92
For now, just supporting `x-nullable`. Once OpenAPI publishes a version with `nullable`, will be very easy to add support for that.
I just picked a light-blue-ish color for "Nullable" in the UI. If you would rather use some other color that is totally ok with me, let me know and I can update the PR or you can do it after in a separate commit.
Let me know if I didn't get to anything that should also be changed for this.
> support "x-nullable" property

- lib/utils/SpecManager.ts
- tests/schemas/api-info-test.json
according to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object) the `basePath` isn't required,
means if they isn't provided it results in an invalid url (the `undefined` part):
this PR corrects the behaviour, so the url would be valid
> makes basePath optional

- README.md
- lib/components/Method/method.ts
- lib/services/options.service.ts
- lib/utils/spec-manager.ts
This allows ReDoc to be used for self-hosted tools where the hostname may not be known.
> Add option to hide hostname in method definition

- lib/services/menu.service.spec.ts
- lib/utils/md-renderer.spec.ts
- lib/utils/md-renderer.ts
- package.json
- tests/e2e/helpers.js
- tests/e2e/redoc.e2e.js
- tests/unit/SpecManager.spec.ts
- yarn.lock
Based off the discussion here #179, adding logic to check if no heading-1 present then reassign the heading-2 to be heading-1. 
This allows code to continue without error. 
Another variation on this would be to leave the heading-2 the user defined but also create a heading-1 in the background this would however lead to a slight dupe within the menu and docs.
> Bugfix/heading safe guard #179

- README.md
- docs/redoc-vendor-extensions.md
- lib/components/ResponsesSamples/responses-samples.ts
- lib/components/SchemaSample/schema-sample.ts
- lib/utils/helpers.ts
- tests/unit/helpers.spec.ts
This PR adds a vendor extension of `x-examples` which allows developers to specify an example for requests.
Right now a JSON example is automatically generated from the schema and this is an awesome feature most of the time, however we have a couple of cases where it would be ideal if we could specify an example (dealing with rather large schema 😞 ).
The value of `x-examples` is the same as the [Example object](http://swagger.io/specification/#exampleObject) from the specification, even though `application/json` (or something JSON-like with #225) is the only "valid" mime type for the time being.
> Support x-examples vendor extension for requests

- build/webpack.common.js
- package.json
- yarn.lock
Fix https://github.com/Rebilly/ReDoc/issues/243
> fix issue with loading https spec

- lib/components/Redoc/redoc.scss
> fix: ul missing css

- lib/utils/md-renderer.ts
I have following OpenAPI yaml which markdown headers are composed of non-ascii characters.
```yaml
swagger: "2.0"
info:
title: サンプルAPI
description: |
サンプルのAPIドキュメントです。
はじめにデベロッパー登録してください。
以下のような形式でエラーを返します。
```
ReDoc will slugify these headers to make permanent links. However non-ascii-only header will be converted into same section names like this. They don't work well as permanent links.
```markdown
```
I committed https://github.com/Joe-noh/ReDoc/commit/32f2f7f744c4ec15fb7b8ba243bf76c8c9970b26. This uses original header title if slugified title is empty. I guess this is simplest solution for this problem. Please let me know if there are any other good options.
Thanks. Joe.
> Slugifying non-ascii headers make duplicate permalinks

- lib/shared/components/StickySidebar/sticky-sidebar.ts
Seems like heights are being incorrectly calculated when initialising page. I've prevented this behaviour by looking at loading class name of redoc-wrap element.
> fix: (#276) Issue with stick sidebar when there is content above reDoc

- package.json
- yarn.lock
With the current version, on macOS, trying to start the local server with NodeJS 8 results in
```
Module build failed: Error: Node Sass does not yet support your current environment: 
OS X 64-bit with Unsupported runtime (57)
```
> use node-sass ^4.5.3, which supports NodeJS 8

- demo/swagger.yaml
- lib/components/Operation/operation.html
- lib/components/Operation/operation.scss
- lib/components/Operation/operation.ts
- lib/components/SideMenu/side-menu-items.html
- lib/components/SideMenu/side-menu-items.scss
- lib/services/menu.service.ts
This PR adds visual hints to deprecated operations which discussed in #286.
> Add special rendering for deprecated operations

- tests/helpers.ts
As per https://developer.mozilla.org/en/docs/Web/API/MouseEvent `true` isn't a valid parameter and causes an error to be thrown in typescript 2.4 (correctly). This set of parameters matches that in the catch below using `document.createEvent`
> Fix event creation

- lib/utils/JsonFormatterPipe.ts
Without this fix, `date-time` fields in examples get output as empty objects.
> In JsonFormatter, output dates as ISO 8601 strings, per OpenAPI spec.

- lib/components/ApiInfo/api-info.scss
> Add `display: inline-block` for `.openapi-button`

- lib/components/ApiInfo/api-info.scss
- lib/components/ApiLogo/api-logo.html
- lib/components/ApiLogo/api-logo.ts
Summary:
* #322: Feature request: Clickable logo that points to specific url
* Add "Return to website" link to the top right that leads to `info.contacts.url` if any.
* Increase padding top for `.api-info-wrapper` when left sidebar is hiding to avoid header overlaying by top menu.
@RomanGotsiy Unfortunately I don't do Angular, so I'm not sure if `lib/components/ApiInfo/api-info.html` is correct.
I, also, added a "Return to website" button, I need it, maybe someone need it, too. (It won't show up if no `url` in `contact` section of spec is present. Also, we can hide it with css `.go-back-link { display: none }`)
And I've noticed that  `.api-info-wrapper h1` becomes overlaid by top menu on small devices (once left sidebar is hiding), so I've increased the top padding for that.
I haven't …
> Closes #322: Feature request: Clickable logo that points to specific url

- lib/components/Redoc/redoc.scss
They're pretty tightly squeezed in there right now.
> Add margins around list-items in markdown

- README.md
Great idea from @ThatBrianDude
> Clearly label version compatibility

- lib/components/ApiInfo/api-info.html
Hi!
I'm not sure if you want such PR, but I've noticed that "Download" button on Safari opens spec instead of downloading. There was `download` attr already, but it didn't work because of `target="_blank"`. With this PR it is working.
Thanks!
> Make HTML5 attr `download` to work on "Download" button

- docs/redoc-vendor-extensions.md
Have seen a number of definitions designed for use with ReDoc using a relative logo URL. This 'breaks' when someone else (e.g. APIs.guru) hosts the API definition.
> Add note that x-logo SHOULD use absolute URLs

- lib/components/ParamsList/params-list.scss
PR to align parameters description up to be more consistent.
Turn this:
Into this:
> Align parameters to match up

- src/styled-components.ts
the media queries helpers use the base theme breakpoints instead of the current theme ones set on the standalone component props, this PR fixes that.
> fix the media queries utils so it gets the values from the current theme

- demo/index.tsx
- demo/webpack.config.ts
- src/components/SelectOnClick/SelectOnClick.tsx
- src/services/OpenAPIParser.ts
* SelectOnClick has been fixed. This was crashing.
* When OpenAPIParser was dereferencing a schema and the ref was not found, it would return undefined. This would crash other segments of the code such as `if (schema.allOf === undefined) {`
> React Rewrite: A couple minor bug fixes

- package.json
When using the alpha build of ReDoc, running in an environment with React 16.2.0 results in an error due to the missing `createContext` API. This PR updates the package.json `peerDependencies` to reflect the need for react >= 16.3
> Modify the peerDependencies to reflect the need for react 16.3.0

- src/services/OpenAPIParser.ts
This PR allows
```
allOf:
- type: array
items:
type: object
properties:
id:
type: string
- type: array
items:
type: object
properties:
name:
type: string
```
And render it as
```
type: array
items:
type: object
properties:
id:
type: string
name:
type: string
```
> MergeAllOf takes items into account

- src/services/OpenAPIParser.ts
Add vendor extension used by swagger-codegen for Swagger 2.0 as an alternative to OpenAPI 3.0 mapping feature.
For example: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/model.mustache
> parse discriminator value from the referenced scheme

- src/components/Fields/FieldDetails.tsx
- src/services/models/Schema.ts
Given the following schema
```
FooCollection:
type: array
items:
type: object
title: Foo
properties:
bar:
type: string
```
This PR renders `Array of object (Foo)`
> Use item's title in array definition

- package.json
This includes the fix for x-discriminator. 
Fixes #496.
> Update swagger2openapi to 3.1.2

- src/services/MarkdownRenderer.ts
- src/services/models/Group.model.ts
- src/utils/__tests__/helpers.test.ts
- src/utils/helpers.ts
The `slugify` function cannot return valid result when input is Unicode such as Korean, Chinese.. etc., so this occurs tag navigation and duplicated key error.
> use original tag name when slugified one is not valid

- cli/README.md
Setting options.theme.colors.main does not work. Digging in the options object revealed that it is options.theme.colors.primary.main.
> Update readme color customization example

- src/components/SideMenu/MenuItem.tsx
- src/components/SideMenu/styled.elements.ts
This pull request fixes an issue where the "PATCH" method does not fit inside the badge very nicely at the cost of some horizontal space for the summary.
**Before:**
**After:**
> Increase badge size slightly so that "PATCH" method fits inside better

- README.md
- src/services/RedocNormalizedOptions.ts
- src/services/models/MediaType.ts
Addresses https://github.com/Rebilly/ReDoc/issues/424
> Fix #424: Add onlyRequiredInSamples option

- src/services/AppStore.ts
The `disposer` field were of `any` type so TS did not catch this.
If `disableSearch` option is set to true, we never set up the mobx observer, effectively leading to `this.disposer` being `undefined`.
> service/AppStore: add null check in dispose method

- demo/openapi.yaml
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
According to #42 , `minItems` and `maxItems` are not yet rendered in the documentation.
This pull request shows the humazined form of `minItems` and `maxItems` next to the type description.
The [suggestion of fgabolde](https://github.com/Rebilly/ReDoc/issues/42#issuecomment-371883853) is followed and "characters" is simply replaced with "items".
Some examples are added to the demo.
> Add support for minLength and maxLength constraint humanization

- README.md
The command to launch ReDoc with Docker had the `-p` values reversed.
According to the Docker Docs, it should be `HOST_PORT:CLIENT_PORT`.
The Nginx service is running on port 80 inside the container, 8080 is the 
port exposed on the host.
> Corrected Docker Port in README.md

- lib/services/schema-normalizer.service.ts
Current versions of ReDoc applications (1.x and 2.x) have an issue to properly display property description if it contains `$ref` to the schema object. At best ReDoc displays the original `description` of the schema object.
For example, this YAML description of [Demo REST API](https://github.com/darklynx/swagger-api-collection/blob/master/api/yaml/prop-desc-demo.yaml):
```YAML
...
definitions:
Company:
type: object
description: Company short description
properties:
name:
type: string
description: Company name
example: Secret agency
ceo:
$ref: '#/definitions/Person'
description: CEO of the company
cto:
$ref: '#/definitions/Person'
description: CTO of the company
employees:
type: array
description: Company employees
items:
$ref: '#/definitions/Person'
visitor:
$ref: '#/definitions/Person' …
```
> Fix for property description with $ref

- README.md
- docs/redoc-vendor-extensions.md
It looks like the OAS spec page changed some of their anchor tags, just fixing the links that I noticed.
> Fix links to OAS spec page

- package.json
Now that marked.js has published a new version you can remove the dependency to specific git commit so we can fetch all dependencies from official releases to npmjs.
> Updated marked to 0.5.2

- docs/redoc-vendor-extensions.md
Goofed one of the links in my last [PR](https://github.com/Rebilly/ReDoc/pull/728), the site handles anchor tags weirdly. I think everything else is correct now :)
> docs: fix link to OpenAPI specification in vendor extensions doc

- README.md
Rebilly's `swagger.json `was renamed to `openapi.json`.  Just checking in a quick fix for the change.
> Fix the demo specUrl

- config/docker/docker-run.sh
When PORT is 8080 and dokcer restart, nginx will listen 80808080
> Incorrect port after restart when PORT is 8080

- src/components/ApiInfo/ApiInfo.tsx
- src/services/OpenAPIParser.ts
This only displays the version if it is specified in the info section:
This is useful for OpenAPI specifications that bundle several APIs that are versioned independently, hence the global version string makes little sense.
> Only display API version if present

- cli/README.md
- cli/index.ts
Hello!
This PR add `templateOptions` param to pass additional data to the custom template using ReDoc `cli`. This is a need to pass, as an example, meta information.
> Add templateOptions param to pass additional data to custom template

- docs/redoc-vendor-extensions.md
**Affected version:**
v2.0.0-rc.2
**Problem:**
The documentation for `x-displayName` ([link](https://github.com/Rebilly/ReDoc/blob/v2.0.0-rc.2/docs/redoc-vendor-extensions.md#x-displayname)) had been added into the middle of the `x-traitTag` section ([link](https://github.com/Rebilly/ReDoc/blob/v2.0.0-rc.2/docs/redoc-vendor-extensions.md#x-traittag)), splitting the original section and moving its example ([link](https://github.com/Rebilly/ReDoc/blob/v2.0.0-rc.2/docs/redoc-vendor-extensions.md#usage-in-redoc-3)) to the wrong extension.
**Solution:**
Just move a couple of lines.
> Fix documentation of x-traitTag extension

- src/utils/jsonToHtml.ts
Follow up for #822 and 04731656 (only escape quotes).
When `example: '{"name":"Guru \ bs"}'` is given...
before:
after:
> fix: escape backslashes in string literals

- config/docker/README.md
By just using the commands from https://hub.docker.com/r/redocly/redoc/ it didn't worked for me. I added the missing docker repository name and changed PWD to pwd as well.
> Fixed docker README: added missing redocly repo name

- src/components/index.ts
It's already exported on line 1
> Remove duplicate re-export from index.ts

- src/components/Parameters/Parameters.tsx
After migrating to ReDoc we noticed that some of descriptions from our OpenAPI 3.0 spec that were previously visible in swagger-ui has disappeared. 
One of the examples is description in requestBody (this missing feature was already referenced in comment to issue https://github.com/Rebilly/ReDoc/issues/598#issuecomment-437287835 and in this issue).
We were able to mitigate this problem by moving relevant descriptions from requestBodies up to request method level, but for the sake of completeness i decided to propose this PR.
Please comment if you are interested in incorporating this feature and if you are ok with this particular implementation.
> Display requestBody description #833

- src/common-elements/fields.ts
- src/components/Fields/Extensions.tsx
This PR:
- Standardises an extension to use the `FieldLabel` component rather than a bespoke one so the style matches
- Removes the `x-` prefix from the extension when presenting the name on the page
- Title cases the unprefixed extension name
- Removes the extraneous `"` quotes from either side of the extension value, so strings like `test` are displayed as `test` and not `"test"`
Before:
(where we're using `x-scope` to annotate the scope required for a particular field to be populated from our API above and beyond the scope needed to access the endpoint itself, which is defined in security objects etc)
After:
> Tidy up non-redoc extension presentation

- src/theme.ts
This PR fixes the typo here:
https://github.com/Rebilly/ReDoc/blob/dc77d8f25e8d9f198eb1135b01eb5b04dc9555ec/src/theme.ts#L169
> fixes typo in error message for detecting a circular dependency in theme.ts

- src/services/MenuBuilder.ts
Fixes #868 
If `x-tagGroups: []` empty array is passed - tag groups should be ignored. Without this PR it hides all the tags.
> Fix: Ignore empty x-tagGroups array

- src/components/Endpoint/styled.elements.ts
As seen in #860 , this PR aims to change the font used in the "path" section of the generated doc, from the "headings" to the "code" font-family.
> fix #860 change fontFamily for EndpointInfo

- README.md
"theme: { colors: { main: '#dd5522' } }" didn't work for me.
> add additional property to theme usage doc

- src/common-elements/headers.ts
- src/theme.ts
I was facing a problem that the heading looks kinda squashed because the `lineHeight` setting for headings are too small. This pull requests adds a theme configuration for the `lineHeight` of the headings.
> Add lineHeight config for headings

- src/components/Fields/EnumValues.tsx
- src/components/Fields/FieldDetail.tsx
This PR fixes some minor presentation issues with enums etc.
> Clean up how field values are displayed

- src/components/Endpoint/Endpoint.tsx
- src/utils/helpers.ts
If ReDoc is initiated on a page containing query strings in the URL, the generated URL is misbehaving as shown on the following image
Live example at https://demo.api-platform.com/?ui=re_doc&spec_version=3
After this change the exposed URL would be `https://demo.api-platform.com/books` as expected
> Remove querystring from exposed URL

- cli/index.ts
I'm hosting an instance of redoc behind an HTTPs proxy at tugboat.qa. If a browser requests a compressed response, redoc-cli doesn't emit a `Content-Type` header. The HTTPs proxy is then inferring a `Content-Type` of `application/octet`, causing browsers to download the page instead of displaying it.
This PR sets the content type for `/`.
> Add missing content type header on compressed responses of /

- src/components/Endpoint/Endpoint.tsx
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
Servers are just displayed in Redoc and are not used to make calls so expanding variables may confuse you that the server doesn't have variables:
e.g.:
`https://{stage}.example.com` - makes it clear that the stage can be configurable
vs  `https://prod.example.com` - you have no way to learn about other stages and that they are configurable
> Revert expanding default server variables

- README.md
Since the redoc react component will not work without core-js, it should be added to the docs
Ref #997
> Add core-js as peer dependency in docs

- src/utils/openapi.ts
This PR simply corrects a typo that happens when the console warns about deepObjects being used incorrectly
> Correct typo of expolde to explode

- cli/index.ts
- cli/template.hbs
there is a hardcode in html template to force load a font family from google. same issue here: https://github.com/Redocly/redoc/issues/356
i dont think it's a good idea because of people in china has GFW there.
so i implement a switch called `disableGoogleFont` to turn it down and let people decide to open it or not. (it's still opening by default).
> feat: add `disableGoogleFont` parameter to cli

- package.json
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
We propose to use [`url-template`](https://www.npmjs.com/package/url-template) instead of [`uri-template-lite` ](https://www.npmjs.com/package/uri-template-lite). `uri-template-lite` seems to be vulnerable for a XSS attack as stated in #1007. I agree this dependency is less maintained then `uri-template-lite`. However, as the approach of this dependency is to generate code on runtime, probably to speed it up (therefore the '-lite'), we do not consider it 'safe'. 
Also corrected a test that was not conform the [spec](https://tools.ietf.org/html/rfc6570#section-3.2.5), and detected by the new `url-template` dependency:
```
X{.list*}          X.red.green.blue
```
Therefore, the following test does not seems to be correct:
```
{ style: 'label', explode: true, expected: …
```
> fix: use url template dependency

- src/components/Endpoint/Endpoint.tsx
- src/components/Schema/Schema.tsx
- src/services/RedocNormalizedOptions.ts
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
Recover server expanding default variables
This reverts commit 7849f7f6b7517275f2b283085ac8174f83dc055d.
> fix(server/variables/default/expanding):

- cli/index.ts
This PR addresses the #797 issue and allows to pass JSON object for cli options as string for the redoc-cli. For example:
```
redoc-cli serve --options='{"theme":{"colors":{"primary":{"main":"orange"}}}}' petstore.yaml
```
will work as well as 
```
node index.js serve --options.theme.colors.primary.main='orange' petstore.yaml
```
> added support for JSON string value for --options CLI argument

- cli/index.ts
This PR adresses #754 issue and allows following CLI format:
```
redoc-cli serve --options=../inc/config.json petstore.yaml
```
in addition to:
```
redoc-cli serve --options='{"theme":{"colors":{"primary":{"main":"black"}}}}' petstore.yaml
redoc-cli serve --options.theme.colors.primary.main=black petstore.yaml
```
In such case, in linked file must be a valid JSON for options. For the example above:
```json
{
"theme": {
"colors": {
"primary": {
"main":"black"
}
}
}
}
```
> Support file name with a JSON object as a value of --options CLI argument

- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
Hello,
I had a look at #1053 and came up with an adjustment such that the innermost item type of a nested array won't be be made plural more than once.
Here's an example output as a result of the change:
Though this degree of nesting seems fairly contrived, some might feel the full display type still looks strange.
I guess an alternative would be to facilitate expansion of members that are arrays, kind of like the following (i.e. `Array of arrays` instead):
However, the above would require a lot more effort from the look of it.
> Fix item type pluralization for nested arrays

- README.md
* Sort by name
* Document `hideSingleRequestSampleTab`
* End option description with `.`
> Improve options documentation

- demo/openapi.yaml
- src/components/Fields/FieldDetails.tsx
**No quotes for default values in header fields.**
In a header field/parameter line Accept-Language, instead of 
`Default: "en-US"`
(which is ugly and just wrong), you now get:
`Default: en-US`
**Spaces around the pattern values.**
Instead of:
`string/^\d+$/`
you now get:
`string /^\d+$/`
Small README improvement.
> Resolve formatting bugs.

- demo/openapi.yaml
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
> feat: display `multipleOf` constrains

- README.md
The link was missing the `-x` part in the `#` anchor.
> Fix link to x-nullable docs from README

- demo/index.tsx
Since this seems like something that happens once in a while, is there a reason to not use a permalink, like linking to the yaml file in the apis.guru repo?
https://raw.githubusercontent.com/APIs-guru/openapi-directory/c8d61eeb3c52504cbe006838093897df20682342/APIs/slack.com/1.2.0/swagger.yaml
> Fixed example slack api url

- cli/index.ts
Instead of using "ReDoc documentation" straight away as the title of the HTML page rendered by `redoc-cli`, it tries to use the specification's title in its info object.
I haven't seen any place to write tests for the cli tool, so I didn't write any.  
However, here are the three possible test cases and expected results: 
Command: `redoc-cli bundle spec.yaml --title "Your Awesome Title"`
OpenAPI spec title: "Another title" | null
HTML page title (result): "Your Awesome Title"
Command: `redoc-cli bundle spec.yaml`
OpenAPI spec title: "Your Awesome Title"
HTML page title (result): "Your Awesome Title"
Command: `redoc-cli bundle spec.yaml`
OpenAPI spec title: null
HTML page title (result): "ReDoc documentation"
I've still made sure that everything was prettified and linted which made me …
> feat(cli): Fallback on the spec's title before falling back on "ReDoc documentation"

- cli/index.ts
- package.json
- tsconfig.json
> chore(cli): Lint and prettify cli/index.ts

- src/services/SearchStore.ts
Blob URLs may be disabled by CORS (ex: #764) but should not block execution when the disableSearch option is true
> fix: do not load SearchWorker if disableSearch is `true`

- e2e/integration/search.e2e.ts
- src/components/SearchBox/SearchBox.tsx
- src/utils/__tests__/openapi.test.ts
Fixes #1027 
Steps taken
- Ran tslint
- Ran all tests
- Ran `yarn prettier`
> fix: Add debounce for 300 ms when searching

- src/components/JsonViewer/JsonViewer.tsx
This PR updates the` collapseAll` method to avoid collapsing whole object/array in JSON preview.
Fixes #1164
> fix: do not collapse top level on Collapse All in json samples

- docs/redoc-vendor-extensions.md
- src/services/models/Schema.ts
- src/types/open-api.d.ts
- src/utils/openapi.ts
This replaces #774 
When the mapping is partial, here the `dog` mapping was removed:
```yaml
discriminator:
propertyName: petType
mapping:
cat: '#/components/schemas/Cat'
kitten: '#/components/schemas/Cat'
bee: '#/components/schemas/HoneyBee'
```
The type `Dog` will be included in addition to the mappings:
The idea is to have an exhaustive mapping, in that case we'd like to ignore non-mapping child classes. I've added a new extension `x-limitToMapping` of type boolean. When used, it excludes the class `Dog` in the following case:
```yaml
discriminator:
propertyName: petType
x-limitToMapping: true
mapping:
cat: '#/components/schemas/Cat'
kitten: '#/components/schemas/Cat'
bee: '#/components/schemas/HoneyBee'
```
will yield the following result:
> feat: add x-explicitMappingOnly extension

- src/services/models/Schema.ts
The fix for #1111 (in https://github.com/Redocly/redoc/commit/6e390f9c7909da0b5d1d6fc571ab4ad92e715d6e) sadly broke the order of mapping entries.
Given the discriminator:
```yaml
discriminator:
propertyName: petType
x-limitToMapping: true
mapping:
dog: "#/components/schemas/Dog"
cat: "#/components/schemas/Cat"
doggy: "#/components/schemas/Dog"
bee: "#/components/schemas/HoneyBee
```
The result is out of order:
Also, if we remove the `Dog` mappings, we end up with the `Dog` class between the mappings:
This PR adds a sort in case of the presence of a mapping. The behavior is quite simple:
- Explicit mappings are prioritized to implicit mappings
```yaml
discriminator:
propertyName: petType
x-limitToMapping: true
mapping:
dog: "#/components/schemas/Dog"
cat: "#/components/schemas/Cat"
doggy: …
```
> fix: sort discriminator entries by mapping order

- demo/index.tsx
Not sure if this is wanted, but [we have now a spec](https://github.com/graphhopper/directions-api-doc/) that we use in production and uses several features of redoc. See [preview](http://redocly.github.io/redoc/?url=https://docs.graphhopper.com/openapi.json).
> demo: new URL for GraphHopper

- cli/index.ts
As mentioned in [this comment](https://github.com/Redocly/redoc/pull/1073#issuecomment-577328022), the `--title` option was never implemented for the `serve` subcommand.
Here are my 3 test cases to show that it works: 
```yml
openapi: 3.0.0
info: {}
paths: {}
```
```sh
redoc-cli serve spec.yml
```
ReDoc Documentation
```yml
openapi: 3.0.0
info:
title: Title given in the file
paths: {}
```
```sh
redoc-cli serve spec.yml
```
Title given in the file
```yml
openapi: 3.0.0
info: {}
paths: {}
```
```sh
redoc-cli serve spec.yml --title "Title given to the command"
```
Title given to the command
```yml
openapi: 3.0.0
info:
title: Title given in the file
paths: {}
```
```sh
redoc-cli serve spec.yml --title "Title given to the command"
```
Title given to the command
> feat(cli): add the --title option to the serve subcommand

- config/docker/README.md
After spending some time figuring it out and finding [this issue](https://github.com/Redocly/redoc/issues/893), I was able to find how to watch files served by redoc via Docker. I'd like to save new developers time with this PR.
> Add "serve and watch" documentation for Docker image

- config/docker/nginx.conf
Increase the security of the nginx server and the served page, by adding the following security headers to the nginx config:
- X-Frame-Options (Disables click jacking by disallowing the page to be run in a frame/iframe)
- X-XSS-Protection (Enables cross site scripting filtering)
- X-Content-Type-Options (Disables MIME sniffing and forces browser to use the type given in Content-Type.)
- Content-Security-Policy (Controls resources the user agent is allowed to load for a given page.)
- Referrer-Policy (Governs which referrer information sent in the Referer header should be included with requests made.)
Additional headers that could be added optionally:
- Strict-Transport-Security (Enforce HTTPS over HTTP)
> Add security headers to nginx config

- docs/redoc-vendor-extensions.md
The file `docs/redoc-vendor-extensions.md` contained a link to `https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#server-object`, which is invalid. I updated it to point to `https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject`
> Updated x-servers link to point to valid location.

- src/common-elements/perfect-scrollbar.tsx
Added [`overscroll-behavior: contain`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) to side menu when native scrollbars used. It will prevent body scrolling when user scrolls over menu using mouse wheel or trackpad.
> Prevent body scrolling when user scrolls side menu

- src/components/Schema/ArraySchema.tsx
Encountered [this issue](https://github.com/Redocly/redoc/issues/1131) in our spec, trying to fix according to suggestion in issue.
This is my first attempt to contribute to redoc (or any TypeScript/JavaScript project) - I hope I'm in the right direction, but I can't seem to build the project locally - tests are failing (on a clean master repo), so please be gentle.
If you can point me to how to add a test for this behavior, I'll gladly do that too.
> add Array size info based on min max Items properties

- package-lock.json
- package.json
- src/common-elements/CopyButtonWrapper.tsx
- src/common-elements/dropdown.ts
- src/common-elements/fields-layout.ts
- src/common-elements/fields.ts
- src/common-elements/linkify.tsx
- src/common-elements/samples.tsx
- src/common-elements/shelfs.tsx
- src/common-elements/tabs.ts
- src/components/CallbackSamples/CallbackSamples.tsx
- src/components/DropdownOrLabel/DropdownOrLabel.tsx
- src/components/Endpoint/Endpoint.tsx
- src/components/Endpoint/styled.elements.ts
- src/components/Fields/Field.tsx
- src/components/GenericChildrenSwitcher/GenericChildrenSwitcher.tsx
- src/components/JsonViewer/JsonViewer.tsx
- src/components/MediaTypeSwitch/MediaTypesSwitch.tsx
- src/components/PayloadSamples/MediaTypeSamples.tsx
- src/components/PayloadSamples/PayloadSamples.tsx
- src/components/PayloadSamples/styled.elements.ts
- src/components/Responses/ResponseTitle.tsx
- src/components/Responses/styled.elements.ts
- src/components/Schema/DiscriminatorDropdown.tsx
- src/components/SelectOnClick/SelectOnClick.tsx
- src/components/__tests__/JsonViewer.tsx
- src/theme.ts
- tsconfig.lib.json
Fixes https://github.com/Redocly/redoc/issues/1280
Fixes https://github.com/Redocly/redoc/issues/1281
Fixes https://github.com/Redocly/redoc/issues/1282
Fixes https://github.com/Redocly/redoc/issues/1283
> fix: fix some accessibility issues

- package-lock.json
- package.json
- src/common-elements/schema.ts
- src/components/SelectOnClick/SelectOnClick.tsx
Fixes #1330 
Fixes #1331 
Fixes #1332
> fix: make elements accessible by keyboard navigation tools

- demo/openapi.yaml
- e2e/integration/menu.e2e.ts
- src/common-elements/shelfs.tsx
- src/components/Operation/Operation.tsx
- src/components/SideMenu/MenuItem.tsx
- src/components/SideMenu/styled.elements.ts
- src/services/Labels.ts
- src/services/MenuBuilder.ts
- src/services/SpecStore.ts
- src/services/models/Operation.ts
- src/services/models/Webhook.ts
- src/types/open-api.d.ts
This PR implements webhooks support.
**Example of usage:**
```yaml
x-webhooks:
newPet:
post:
summary: New pet
description: Information about a new pet in the systems
operationId: newPet
tags: 
- pet
requestBody:
content:
application/json:
schema:
$ref: "#/components/schemas/Pet"
responses:
"200":
description: Return a 200 status to indicate that the data was received successfully
```
**Layout:**
> feat: add webhooks support

- src/components/SideMenu/styled.elements.ts
Closes https://github.com/Redocly/redoc/issues/1180.
See https://github.com/Redocly/redoc/issues/1180#issuecomment-676797731 for the `width` change.
See https://github.com/Redocly/redoc/issues/1180#issuecomment-634545588 for the `font-family` change.
---
Setting units in `px` and `(r)em` uses the CSS-defined `font-size` units (in this case `7px`) and not the computed `font-size`, which means the label size does not scale with the increased minimum font sizes users can set in their browser's settings. Minimum font size is a setting in pretty much every browser on Windows, Linux and MacOS and is likely set to `None` by default.
If a user sets the minimum font size above `7px` (for example `10px`) then the label width (a static `32px`) becomes too short for the text width.
The `ex` unit is …
> fix: scale sideMenu labels according to computed font size

- package.json
In package.json we adjusted the styled-component peerDependecy from 4.11 to 5.1.1 to match the version listed in devDependency.
> Fix #1387: Update the styled-components peerDependency 

- config/docker/Dockerfile
- config/docker/README.md
In order to be able to run the Docker container in OpenShift a few tweaks must be done.  
I did them in the `Dockerfile` and added explanations to the associated `Readme.md`.
I think the changes done may not bring regressions, and I thought that it may may have been overkill to introduce a new Docker image for this. Let me know if you prefer otherwise.  
I didn't change the user though as the container seems to work fine even when running as `root`, and I didn't want to introduce potential regressions to non-OpenShift users.
>  feat: Dockerfile compatible with OpenShift (#1407)

- README.md
Per https://github.com/Redocly/redoc/issues/1189#issuecomment-606857342 the latest version works now, and the currently-specified version doesn't.
> docs: unqualify mobx version for react usage

- src/common-elements/fields-layout.ts
- src/components/SecurityRequirement/SecurityRequirement.tsx
- src/styled-components.ts
> fix: make schema layout more responsive on small screen

- src/components/SecuritySchemes/SecuritySchemes.tsx
The official name of the OpenID Connect security scheme does not contain a space between 'Open' and 'ID', see https://openid.net/connect/.
> Fixed the name of the OpenID Connect security scheme

- src/common-elements/PrismDiv.tsx
- src/common-elements/fields.ts
- src/common-elements/mixins.ts
- src/common-elements/samples.tsx
- src/components/PayloadSamples/styled.elements.ts
- src/theme.ts
> chore: increase colors contrast to make them more accessible

- src/components/Fields/FieldContstraints.tsx
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
Hello,
Fixes #1353.
Schemas which define `uniqueItems` should now generate a field constraint indicator.
For the example provided in the linked issue, the visual output looks like the following:
---
I also noticed `ArraySchema` tries to indicate array-type constraints. Specifically, it only covers the `minItems` and `maxItems` constraints.
https://github.com/Redocly/redoc/blob/1fdfd1353dfc07aca5f5d55e5e2195648bde6e2b/src/components/Schema/ArraySchema.tsx#L21
I haven't dug too deeply into this, but with a simple schema such as:
```yaml
type: array
items:
type: number
minItems: 1
```
I'd expect to see something like the following (based on the code), but I don't:
Anyway, I'm happy to follow-up and do something about the latter if it's indeed unexpected behaviour.
> Add field constraint indicator for uniqueItems

- src/components/Endpoint/Endpoint.tsx
> fix: remove duplicated slash if hideHostname option enabled

- README.md
Noticed there were more extensions on https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md than in the README, this PR adds them to the readme
> Add 3 vendor extensions to list

- README.md
Taken from https://redoc.ly/docs/cli/configuration/reference-docs/, just filtered to only CE options.
> Document theme options

- src/utils/highlight.ts
> fix: pass boolean and number values as a string in highlight function

- cli/index.ts
> fix: broken paths when budle or serve using cli

- src/components/Markdown/styled.elements.tsx
There was a missing semicolon in the CSS. As is, it works without any issue, but if any minification happens, it can result in this:
> Added missing semicolon

- cli/index.ts
The correct full path provided for load and bundle definition.
It’s much easier to figure out what’s wrong, especially when getting the error: _**no such file or directory**_.
> fix: right absolute path for load and bundle definition

- src/standalone.tsx
Hi,
this PR fixes the problem described in #1248, by parsing the theme string as json.
Example:
```
<html>
<body>
<redoc spec-url="../demo/openapi.yaml" native-scrollbars theme='{"colors": {"primary": { "main": "#FF5733"}}}'></redoc>
<script src="../bundles/redoc.standalone.js"></script>
</body>
</html>
```
> fix 1248: parse json theme string for standalone tag

- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
resolves #1270
Show path instead of `<no summary>` in sidebar menu
> Improve operational summary

- .github/sync.yml
- .github/workflows/sync.yml
This feature enables `docs` folder synchronization between Redoc `docs` directory and Redocly documentation repository.
If you push changes to the `docs` folder, a pull request to Redocly documentation repository will be automatically created.
> feat: added git folder sync config

- .github/workflows/sync.yml
This commit adds new docs sync flow - without PR creation. New docs changes will be directly pushed into the docs repo.
> chore: changed docs sync flow

- cli/README.md
This PR makes several small improvements to the cli/README.md file:
- Break some long lines
- Add some articles (the, a)
- Add a couple links for additional context
- Expand the SSR acronym
- Describe what the `--watch` option does
> Improve the redoc cli README

- src/components/ApiInfo/ApiInfo.tsx
- src/components/RequestSamples/RequestSamples.tsx
- src/components/ResponseSamples/ResponseSamples.tsx
- src/components/Responses/ResponsesList.tsx
- src/services/Labels.ts
Added localization for some labels
> Added localization for some labels

- cli/npm-shrinkwrap.json
This PR bumps `npm-shrinkwrap` to `v0.12.2` so that can match the already bumped `package.json`: https://github.com/Redocly/redoc/blob/master/cli/package.json#L3
> fix: Bump npm-shrinkwrap

- src/components/SecurityRequirement/SecurityRequirement.tsx
- src/components/__tests__/SecurityRequirement.test.tsx
Fixes [#1631](https://github.com/Redocly/redoc/issues/1631)
> fix: Handle emtpy object in security array

- src/components/RedocStandalone.tsx
- src/services/RedocNormalizedOptions.ts
fixes https://github.com/Redocly/redoc/issues/1670
> fix: hideLoading options in redoc standalone

- src/components/Schema/Schema.tsx
- src/services/models/Schema.ts
When 3.1 was implemented all nullable object fields were not displayed at all, instead object or null was shown.
```
sub:
description: Test Sub Category
type: [object, null]
properties:
prop1:
type: string
description: text of description
```
> fix: nullable object's fields were missing

- CHANGELOG.md
add changelog for v2.0.0-rc.56
> chore: add change log for v2.0.0-rc.56

- docs/quickstart/intro.md
> docs: fix broken links in intro

- README.md
Since my updates to the Redoc documentation have been published, I thought it would be a good idea to start updating the README file. One of the main ways I updated it was by removing the content that is now documented and including a link instead. I also did some other minor cleanup. I plan to do more work on the README in another PR.
I have a task on my GitHub project board. https://github.com/HCloward/redoc/projects/1#card-67733561
n/a
n/a
n/a
> [GSOD]Removes content that is now in documentation and adds link to docs

- e2e/integration/menu.e2e.ts
- src/services/MenuStore.ts
fixed https://github.com/Redocly/redoc/issues/1703
> fix: scrolling to the first item

- package.json
- src/fs.empty.js
- src/services/SearchWorker.worker.ts
- webpack.config.ts
fixed https://github.com/Redocly/redoc/issues/1584
> fix: add browser build for webpack 5

- src/components/SideMenu/MenuItem.tsx
- src/services/MenuStore.ts
- src/services/RedocNormalizedOptions.ts
- src/services/models/Group.model.ts
- src/services/models/Operation.ts
We found an requirement that we want the path to be shown in the sidebar.
If this option is enabled, it displays a path in the sidebar instead of summary.
Usage:
```js
<RedocStandalone
spec={props.spec}
options={{
scrollYOffset:'.navbar',
nativeScrollbars: true,
sideNavStyle: 'summary-only' or 'path-only'
}}
```
sideNavStyle == 'summary-only'
sideNavStyle == 'path-only'
> Use an option usePathInSidebar

- src/components/Operation/Operation.tsx
fixed https://github.com/Redocly/redoc/issues/1756
> fix: fix scroll in example dropdown

- src/components/SideMenu/MenuItem.tsx
- src/components/SideMenu/SideMenu.tsx
- src/utils/dom.ts
Scrolling the documentation on Chrome seems to be broken in certain configurations (e.g. when Experimental Web Platform Features is enabled).
This seems to be caused by a faulty `scrollIntoViewIfNeeded` implementation (https://github.com/Redocly/redoc/issues/1714#issuecomment-897420205).
There already is a polyfill/implementation for the function in the codebase that works correctly in Chrome, so this changes things to always use that implementation instead of the possibly buggy native one.
Fixes #1714
Refs #1742 (can't say it outright fixes it, didn't test on mobile)
Seems to work on my Chrome!
- by hand 
- no new code, no new tests
> Fix Chrome scrolling by using alternate scrollIntoViewIfNeeded

- src/components/Operation/Operation.tsx
- src/services/models/RequestBody.ts
- src/types/open-api.ts
- src/utils/__tests__/openapi.test.ts
- src/utils/openapi.ts
fix: x-examples for request body param does not display #1743
> fix: x-examples for request body param does not display #1743

- src/components/Responses/Response.tsx
- src/components/Responses/ResponseDetails.tsx
- src/services/__tests__/models/Response.test.ts
- src/services/models/Response.ts
- src/types/open-api.ts
If you appreciate this contribution, please add a `hacktoberfest-accepted` Label to the PR, so it'll be tracked
> Added support for showExtensions and $ref for Responses

- src/services/MenuBuilder.ts
- src/services/RedocNormalizedOptions.ts
- src/utils/index.ts
- src/utils/sort.ts
Already documented but is currently `NO-OP` and not implemented
`sortOperationsAlphabetically` and `sortTagsAlphabetically `.
Allows sorting operations in sidebar menu according to their `name`
configured which is by default `summary` from Swaggerspec
TLDR:
Following commit adds support for `sortOperationsAlphabetically` and `sortTagsAlphabetically ` already
documented but not implemented here: https://redoc.ly/docs/api-reference-docs/guides/migration-guide-2-0/#automated-sorting
> MenuBuilder: Add support for `sortOperationsAlphabetically` and `sortTagsAlphabetically `

- cli/index.ts
redoc-cli: add the ability to define `host` with option `-h` or `--host`
> feat: redoc-cli add host option

- e2e/integration/menu.e2e.ts
- src/components/Responses/Response.tsx
When you clicked on a response object you would get the following error.
> Uncaught TypeError: can't access property "expanded", this is undefined
No reference
Added some cypress tests
> fix: Response objects couldn't open

- README.md
Added supported options to the readme file. we support these options and have them in the documentation.
> chore: add supported options to the readme file

- src/services/OpenAPIParser.ts
- src/services/__tests__/OpenAPIParser.test.ts
- src/services/__tests__/__snapshots__/OpenAPIParser.test.ts.snap
- src/services/__tests__/fixtures/3.1/schemaDefinition.json
- src/services/__tests__/models/Schema.test.ts
fixes: https://github.com/Redocly/redoc/issues/1862
`openapi.yaml`
```
openapi: 3.1.0
info:
title: Try to reproduce
version: 1.0.0
servers:
- url: example.com
tags:
- name: test
x-displayName: The test Model
description: |
<SchemaDefinition schemaRef="#/components/schemas/test" />
paths:
/newPath:
post:
requestBody:
content: 
application/json:
schema:
$ref: "#/components/schemas/test"
responses:
200:
description: 'all ok'
components:
schemas:
test:
$ref: ./test.yml#/Test
```
`test.yaml`
```
Test:
type: object
properties:
test:
type: string
```
> fix: external ref in schema definition

- package-lock.json
- package.json
update openapi-sampler to v1.2.1
> chore: update openapi-sampler to v1.2.1

- README.md
- src/components/StickySidebar/ChevronSvg.tsx
- src/components/StickySidebar/StickyResponsiveSidebar.tsx
- src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap
- src/services/RedocNormalizedOptions.ts
- src/theme.ts
fixes https://github.com/Redocly/redoc/issues/1850
added availability to customize FAB:
- theme property for changing background color and icon color for the FAB
```
fab: {
backgroundColor: 'red',
color: 'white',
}
```
- property `hideFab` for non-display floating action button.
> fix: improve customization fab

- src/components/Fields/ArrayItemDetails.tsx
fixes: https://github.com/Redocly/redoc/issues/1919
We had the wrong syntax for "<" and ">" quotes.
> fix: sanitize array of items

- package.json
- src/common-elements/schema.ts
- src/components/Schema/OneOfSchema.tsx
- src/components/__tests__/OneOfSchema.test.tsx
- src/components/__tests__/__snapshots__/OneOfSchema.test.tsx.snap
- src/components/testProviders.tsx
Fix: deprecated badge on one of/any of buttons
> Fix: deprecated badge on one of any of buttons 

- cli/npm-shrinkwrap.json
- cli/package.json
update redoc-cli version to 0.13.9
> chore: cli-v0.13.9

- src/components/SecurityRequirement/SecurityRequirement.tsx
Simply moved the comma separating scope names outside of the code block in the SecurityRequirement component
Before:
After:
> fix: move comma out of code block in SecurityRequirement.tsx

- README.md
- src/services/RedocNormalizedOptions.ts
- src/services/models/Operation.ts
As with most companies that use OpenAPI we make use of the `operationId` to actually know what code to call through auto-generated code, which made this library unusable for generating documentation despite all the other benefits.
Simply added an option to the enum arguments to allow it to display the `operationId` - which is marked as optional in the spec, so provided a fallback to the `path` (the Summary is not useful in technical documentation), and added to the documentation.
No testing has been added for this - as I couldn't find any tests for the already existing functionality - the already existing tests have enough problems that my best comment is "this didn't break anything that wasn't already broken".
> feat: Add support for displaying operationId in the sidebar

- cli/npm-shrinkwrap.json
- package-lock.json
fixed: https://github.com/Redocly/redoc/issues/1941
We should update `minimist` for securing reasons.  In `npm` they write about that too.
We have `minimist` like dependency in `handlebars`. Seems they revert commit with include `minimist` but we don't know when it'll release the next version.
> chore: update minimist for security reasons

- README.md
- src/components/SideMenu/styled.elements.ts
- src/theme.ts
- Add `activeBackgroundColor` and `activeTextColor` to `groupItems ` and `level1Items`
- Leave general `activeTextColor` for all sidebar for compatibility
- Rename `menu` to `sidebar` in readme
> feat: theme add sidebar activeBackgroundColor and activeTextColor

- src/services/MarkdownRenderer.ts
fixes: https://github.com/Redocly/redoc/issues/1952.
In [#1845](https://github.com/Redocly/redoc/pull/1845) we improve our build heading regex but not include all CRLF symbols. This PR should fix it.
```yaml
{
"openapi": "3.0.1",
"info": {
"title": "Minimal Example JSON",
"description": "# Getting Started\r\n## Authentication\r\nAll API Requests _must_ contain an Authorization Header with a valid access token",
"contact": {
"name": "Name",
"email": "email@example.com"
},
"version": "v3.0: 3.10.0.0"
}
}
```
**Before**
**After**
> fix: improve markdown render with CRLF

- README.md
- Rename from OpenAPI CLI to Redocly CLI
- Fix links to Redoc quickstart and deployment guides.
> docs: update the README with correct links

- demo/index.tsx
- package-lock.json
- package.json
- src/services/OpenAPIParser.ts
- src/services/models/Example.ts
- src/utils/helpers.ts
- src/utils/loadAndBundleSpec.ts
- webpack.config.ts
> Pitch Redoc 2.0
Fix **Webpack 5.0** issue in **CRA** when using `RedocStandalone` componenent.
Also related to https://github.com/Redocly/redoc/issues/1820
> chore: make Redoc lib compatible with Webpack 5

- package-lock.json
- package.json
upgrade openapi-sampler to v1.2.3 for fix issue with oneOf example
fixes https://github.com/Redocly/redoc/issues/1999
> chore: upgrade openapi-sampler to v1.2.3

- src/common-elements/fields-layout.ts
- src/common-elements/fields.ts
- src/common-elements/shelfs.tsx
- src/components/Fields/Field.tsx
- src/services/__tests__/fixtures/3.1/patternProperties.json
- src/services/__tests__/models/Schema.test.ts
- src/services/models/Schema.ts
- src/types/open-api.ts
- src/utils/openapi.ts
Implements the ability to display **patternProperties**. 
Closes https://github.com/Redocly/redoc/issues/1983
> feat: display patternProperties

- .github/workflows/e2e-tests.yml
- .github/workflows/main.yml
- .github/workflows/publish-cli.yml
- .github/workflows/publish.yml
- .github/workflows/sync.yml
- .github/workflows/unit-tests.yml
This PR updates GitHub Actions to their latest major versions. Main change is they are all now using Node 16 internally instead of 12, which was EOL at the end of April.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/cache` can be [found here](https://github.com/actions/cache/releases)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
- Releases for `actions/upload-artifact` can be [found here](https://github.com/actions/upload-artifact/releases)
- Releases for `actions/download-artifact` can be [found here](https://github.com/actions/download-artifact)
This PR also changes the `actions/checkout` action in `sync.yml` to reference the action by a …
> ci: update github actions

- cli/npm-shrinkwrap.json
- cli/package.json
> chore: cli-v0.13.14

- src/services/OpenAPIParser.ts
- src/services/__tests__/OpenAPIParser.test.ts
- src/services/__tests__/fixtures/mergeAllOf.json
after releasing the conditional operators we have a problem with merging oneOf, anyOf, and other parts of the schema.
fixes https://github.com/Redocly/redoc/issues/2017
> fix: merge allOf in correct order

- .github/workflows/publish.yml
- README.md
- docs/deployment/html.md
- docs/quickstart.md
- package.json
- scripts/publish-cdn.sh
- scripts/version.js
- add Redoc to Redocly CDN
- create CI/CD for automation deployment
- update docs
> feat: add Redoc to Redocly CDN

- demo/openapi-3-1.yaml
- demo/openapi.yaml
- package-lock.json
- package.json
- src/components/Fields/ArrayItemDetails.tsx
- src/components/Parameters/Parameters.tsx
- src/components/Responses/ResponseDetails.tsx
- src/components/Schema/ArraySchema.tsx
- src/services/OpenAPIParser.ts
- src/services/__tests__/fixtures/3.1/prefixItems.json
- src/services/__tests__/fixtures/arrayItems.json
- src/services/__tests__/models/Schema.test.ts
- src/services/models/Schema.ts
- src/types/open-api.ts
- src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap
- src/utils/helpers.ts
- src/utils/openapi.ts
fixes: https://github.com/Redocly/redoc/issues/1908
- add support items can be array
- add support prefixItems for OpenApi 3.1
- update openapi-sampler to v1.3.0
TODO: fix examples
**OpenApi 3.1**
```yaml
addresses:
type: array
minItems: 0
maxLength: 10
prefixItems:
- type: object
properties:
city:
type: string
minLength: 0
country:
type: string
minLength: 0
street:
description: includes build/apartment number
type: string
minLength: 0
items:
type: string
```
**OpenApi 3.0**
```yaml
addresses:
type: array
minItems: 0
maxLength: 10
items:
- type: object
properties:
city:
type: string
minLength: 0
country:
type: string
minLength: 0
street:
description: includes build/apartment number
type: string
minLength: 0
additionalItems:
type: string
```
> feat: add support prefix items

- src/components/SecurityRequirement/OAuthFlow.tsx
- src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap
- src/services/__tests__/fixtures/3.1/prefixItems.json
- src/services/__tests__/fixtures/arrayItems.json
- src/services/__tests__/models/Schema.test.ts
- src/services/models/Schema.ts
fix https://github.com/Redocly/redoc/issues/2034
_**Before**_
**_After_**
> fix: nested items with refs

- CHANGELOG.md
- package-lock.json
- package.json
update `Redoc` to v2.0.0-rc.72
> chore: v2.0.0-rc.72

- cli/npm-shrinkwrap.json
- cli/package.json
update `redoc-cli` to v0.13.16
> chore: cli-v0.13.16

- e2e/integration/search.e2e.ts
- src/components/SideMenu/MenuItems.tsx
The sidebar navigation uses `menuItem` but without the correct grouping parent role, instead using a `navigation` role.
The use of the `navigation` role on the `ul` also changes the role of that element from an implicit list to an explicit non-list, so rendering the implicit child list items without a correctly named parent.
Before:
After:
> Mis-nesting of aria roles on sidebar navigation

- package-lock.json
- package.json
Resolve dependency conflict for `npm i` and `npm ci` commands. It was related to the latest version of node.js (16.15.1)
_Before_
> fix: resolve dependency conflict in installing

- src/components/__tests__/__snapshots__/DiscriminatorDropdown.test.tsx.snap
- src/services/OpenAPIParser.ts
- src/services/__tests__/models/RequestBody.test.ts
- src/services/__tests__/models/Schema.test.ts
- src/services/__tests__/models/__snapshots__/Schema.test.ts.snap
fix: https://github.com/Redocly/redoc/issues/2079
```yaml
openapi: 3.0.3
info:
version: 0.0.1
title: Test API
servers: []
tags:
- name: Order
paths:
/orders:
summary: Product ordering
post:
tags:
- Order
summary: Create order
description: |
Create an order
operationId: createProductOrder
requestBody:
$ref: "#/components/requestBodies/Order"
responses:
"201":
$ref: "#/components/responses/OrderCreated"
components:
schemas:
ProductOfferingId:
description: Original description for type `ProductOfferingId` which should have
been overridden
type: string
example: SOME_PRODUCT
AccountId:
description: >
Original description for type `AccountId` which should have been
overridden (type with `readOnly: true`)
type: string
readOnly: true
example: "123456789"
ProductOrder:
description: |
Represents an …
```
> fix: property with nested allOf

- src/components/Endpoint/Endpoint.tsx
- src/utils/helpers.ts
- src/utils/openapi.ts
fixes: https://github.com/Redocly/redoc/issues/2090
After:
> fix: operation url in static page

- src/utils/__tests__/openapi.test.ts
- src/utils/helpers.ts
- src/utils/openapi.ts
This PR corrects endpoint URLs (the issue #649)
> Fix #649: correct URLs of OperationModel servers

- src/services/OpenAPIParser.ts
- src/services/__tests__/models/Schema.test.ts
- src/services/__tests__/models/helpers.ts
fix: https://github.com/Redocly/redoc/issues/2059
openapi-factored.yaml:
openapi-allof.yaml:
> fix: enum dublication

- docs/deployment/react.md
Currently getting a 404 when hitting this link on the deployed site
- [ X] Code is linted
- [X ] Tested
- [X ] All new/updated code is covered with tests
> Fixing 404 on the documentation page

- cli/README.md
- cli/index.ts
`@redocly/openapi-cli` renamed to `@redocly/cli`. We improve the deprecation message about that.
> chore: improve deprecation message in serve command

- src/components/SecurityRequirement/SecurityRequirement.tsx
fixes https://github.com/Redocly/redoc/issues/2102
```yaml
openapi: 3.0.3
info:
title: book API
version: 1.0.0
paths:
"/book/{bid}":
get:
description: new description
operationId: get_book_book__int_bid__get
parameters:
- description: book id
in: path
name: bid
required: true
schema:
description: book id
title: Bid
type: integer
responses:
'200':
content:
application/json:
schema:
"$ref": "#/components/schemas/BookResponse"
text/csv:
schema:
type: string
description: OK
security:
- jwt: []
- oauth2:
- write:pets
- read:pets
- basic1:
scheme: basic
type: http
summary: new summary
tags:
- book
tags:
- description: Some Book
name: book
components:
schemas:
BookBodyWithID:
properties:
age:
description: Age
maximum: 4
minimum: 2
title: Age
type: integer
author:
description: Author
maxLength: 4 …
```
> fix: handle error if security scopes is invalid

- src/services/OpenAPIParser.ts
- src/services/__tests__/models/Response.test.ts
- src/services/__tests__/models/Schema.test.ts
fixes: https://github.com/Redocly/redoc/issues/2042
Seems it is broken when we override recursive check logic.
```json
{
"openapi": "3.1.0",
"info": {
"title": "AA",
"version": "1.0"
},
"paths": {
"/test": {
"get": {
"operationId": "test",
"responses": {
"200": {
"content": {
"application/json": {
"schema": {
"type": "object",
"properties": {
"testAttr": {
"description": "Overriden description",
"$ref": "#/components/schemas/Test"
}
}
}
}
}
}
}
}
},
},
"components": {
"schemas": {
"Test": {
"type": "object",
"description": "Refed description"
}
}
}
}
```
> fix: sibling for openapi 3.1

- src/services/MarkdownRenderer.ts
- src/services/__tests__/MarkdownRenderer.test.ts
- src/services/__tests__/models/ApiInfo.test.ts
- src/services/models/ApiInfo.ts
fixes: https://github.com/Redocly/redoc/issues/2118
fixes: https://github.com/Redocly/redoc/issues/1925
- [] Code is linted
- [] Tested
- [] All new/updated code is covered with tests
> fix: duplication of title

- package-lock.json
- package.json
- src/components/SearchBox/SearchBox.tsx
- src/services/__tests__/models/Schema.circular.test.ts
- src/services/models/Schema.ts
fixes https://github.com/Redocly/redoc/issues/2114
fixes https://github.com/Redocly/redoc/issues/2107
fixes https://github.com/Redocly/redoc/issues/2122
[openEO.json.zip](https://github.com/Redocly/redoc/files/9251150/openEO.json.zip)
```yaml
openapi: 3.1.0
info:
version: 1.0.0
title: Swagger Petstore
summary: My lovely API
termsOfService: 'http://swagger.io/terms/'
tags:
- name: pet
description: Everything about your Pets
- name: store
description: Access to Petstore orders
- name: user
description: Operations about user
- name: webhooks
description: Everything about your Webhooks
- name: store_model
x-displayName: The Order Model
description: |
<SchemaDefinition schemaRef="#/components/schemas/Order" exampleRef="#/components/examples/Order" showReadOnly={true} showWriteOnly={true} /> …
```
> fix: problem in rc-74

- .github/workflows/publish-cli.yml
- .github/workflows/publish.yml
we should also make install `cli` in publish script.
related to https://github.com/Redocly/redoc/runs/7766686742?check_suite_focus=true
> chore: add install cli to publish actions

- src/components/SideMenu/styled.elements.ts
fix: "API Docs By Redocly" overlapping last element in sidebar
`Before`
`After`
> fix: "API Docs By Redocly" overlapping last element in sidebar

- src/components/SecurityRequirement/SecurityHeader.tsx
- src/components/__tests__/SecurityRequirement.test.tsx
Representing optional authentication on endpoint don't display properly.
After fix 
```
security:
- {}
- basic: []
```
or
```
security:
- basic: []
-  {}
```
Should be displayed properly
https://github.com/Redocly/redoc/issues/2117
Unit test added
for manual testing, modify openapi.yaml
```
security:
- api_key: []
```
to
```
security:
- {}
- api_key: []
```
> fix: Optional authentication not rendered properly (#2117)

- scripts/publish-cdn.sh
When downloading the redoc JS from redoc.ly CDN (e.g. https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js) the `Content-Type` header in the response is missing `'charset=utf-8'`, causing the file to be displayed with garbled characters.
I faced the issue in my project and found that it was indirectly reported multiple times over the years, as can be seen in https://github.com/Redocly/redoc/issues/29.
The solution proposed in https://github.com/Redocly/redoc/issues/213#issuecomment-282761418 is just a workaround and I'm actually not sure why it works for other people because according to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset, "UTF-8 is the only valid encoding for HTML5 documents" anyway.
- `aws-cli` doesn't automatically detect the charset …
> fix: encoding issue in CDN responses

- src/services/__tests__/models/Schema.circular.test.ts
- src/services/models/Schema.ts
When specific child schema is mentioned in anyOf or oneOf most likely it is meant to be the specific instance and not be discriminated. 
Fixes https://github.com/Redocly/redoc/issues/2133
Added a test.
> fix: do not use discriminator when specific schema was referenced in oneOf or anyOf

- src/services/OpenAPIParser.ts
- src/services/__tests__/__snapshots__/OpenAPIParser.test.ts.snap
- src/services/__tests__/models/Schema.circular.test.ts
fixes: https://github.com/Redocly/redoc/issues/2135
```yaml
openapi: 3.0.0
servers:
- url: //petstore.swagger.io/v2
description: Default server
info:
description: |
Recursion
version: 1.0.0
title: Recursion
x-logo:
url: 'https://redocly.github.io/redoc/petstore-logo.png'
altText: Petstore logo
license:
name: Apache 2.0
url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
- name: pet
description: Everything about your Pets
x-tagGroups:
- name: General
tags:
- pet
paths:
/pet:
parameters:
- name: Accept-Language
in: header
description: 'The language you prefer for messages. Supported values are en-AU, en-CA, en-GB, en-US'
example: en-US
required: false
schema:
type: string
default: en-AU
- name: cookieParam
in: cookie
description: Some cookie
required: true
schema:
type: integer …
```
> chore: add test for handle circular

- src/components/ContentItems/ContentItems.tsx
- src/components/Markdown/AdvancedMarkdown.tsx
- src/services/MarkdownRenderer.ts
- src/services/MenuBuilder.ts
* Fix the parentId error of markdown header
* The same markdown title in different directories of the current version will generate the same index
* Before
* After
> fix: markdown parent name

- .github/CONTRIBUTING.md
- .github/workflows/publish-cli.yml
- .github/workflows/sync.yml
- README.md
- cli/README.md
- demo/index.tsx
- demo/openapi-3-1.yaml
- demo/openapi.yaml
- demo/swagger.yaml
- docs/deployment/docker.md
- src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap
we renamed the master branch to main.
> chore: rename master branch to main

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
> chore: v2.0.0

- README.md
Also add missing punctuation to warning, and change example CDN link to the now-released [2.0.0](https://github.com/Redocly/redoc/releases/tag/v2.0.0).
> Update capitalization in README: ReDoc → Redoc

- demo/index.tsx
Currently the demo at https://redocly.github.io/redoc/ still uses the old logo:
This PR changes the demo code to use the new logo:
Related changes:
- commit c4564de324d78c86e4436cf7ee0aa5b8c63f48ca from PR #1748 (/cc @HCloward)
- PR #2166
- Probably more, but I didn't dig further into the git history :smile:
> demo/index.tsx: Update to use new Redoc logo

- src/components/SchemaDefinition/SchemaDefinition.tsx
- src/components/__tests__/SchemaDefinition.test.tsx
This change allows hiding the examples of a schema definition.
This is useful if the schema is not part of the API but an external resource like a configuration file. As these may have to be created in a different format, a `json` example would only confuse the user.
> feat: add option to hide the example code when using the `SchemaDefinition` component

- custom.d.ts
- src/components/DropdownOrLabel/DropdownOrLabel.tsx
- src/services/OpenAPIParser.ts
- src/utils/object.ts
This was declared in the local stubs file but not shipped, meaning that consumers with typescript libchecking enabled would have to also add the GenericObject definition to their local stubs file.
This commit inlines the definition where necessary, or replaces it with object where appropriate.
Fixes #2171
> Remove GenericObject shim

- custom.d.ts
return GenericObject for `redoc-cli`. We should remove it after releasing the next version of CLI.
> chore: return genericObject for cli

- src/components/StoreBuilder.ts
fix: https://github.com/Redocly/redoc/issues/2025
> fix: call onLoaded if specs are not found

- .github/CONTRIBUTING.md
While preparing to look into a bug in the redoc UI, I followed the setup instructions in `CONTRIBUTING.md` and found that `npm start` will not function unless I install the dependencies of the `cli` package.
It seems like the UI is directly importing code from the CLI without reyling on the CLI as a dependency, so CLI's dependency on `update-notifier` is not tracked and the dev server can't transpile the UI because the import is not resolved, unless I first install the dependencies of the CLI.
Since I know nothing about this repo yet, I chose to update the developer setup instructions rather than try to understand the dependency issue more deeply.
To repro the issue, just follow the setup instructions in `CONTRIBUTING.md` after a fresh clone. Note that the UI crashes. Then perform the …
> Update developer setup with new dependency

- src/components/Fields/Field.tsx
Fixes #2223 
Summary: Labels and accessible labes should correspond. The use of `expand property` instead of `expand {name}` breaks this WCAG rule.
Testing the issue this PR resolves requires using SiteImprove or the [SiteImprove Chrome extension](https://chrome.google.com/webstore/detail/siteimprove-accessibility/djcglbmbegflehmbfleechkjhmedcopn?hl=en) 
AND it requires using another example than the PetStore as it for some reason crashes the extension.
I have tried outlining the issue i the issue and have tested that this change resolves the issue locally.
I'm not able to get this projects test running fully locally. Problems with `update-notifier` even after trying to bind it and change node versions. As I understood it there are some problems with this module currently?
If you have any …
> Improve accessible label by using the property name

- cli/npm-shrinkwrap.json
redoc-cli currently depend on version 4.1.0 of http-cache-semantics which currently gives a high severity warning ([CVE-2022-25881](https://github.com/advisories/GHSA-rc47-6667-2j5j)). This just bumps the version to 4.1.1 where the problem has been adressed.
> chore: bump http-cache-semantics to 4.1.1

- README.md
- cli/README.md
- cli/index.ts
- cli/npm-shrinkwrap.json
- cli/package.json
- e2e/integration/search.e2e.ts
We deprecate `redoc-cli` and move our focus to Redoc.
Instead of `redoc-cli` you can use [`@redocly/cli`](https://www.npmjs.com/package/@redocly/cli).
```bash
redoc-cli serve <spec> -> @redocly/cli preview-docs <spec>
redoc-cli bundle/build <spec> -> @redocly/cli build-docs <spec>
```
remove update-notifier. Fixes https://github.com/Redocly/redoc/issues/2185
> feat: add deprecation label to redoc-cli

- cli/README.md
> docs: fix typo in CLI readme

- demo/openapi-3-1.yaml
In the demo schema `openapi-3-1.yaml` operations updateUser and deleteUser lack successful response descriptions.  
This PR adds 200 and 204 codes for them.
> add some success response codes to openapi-3-1.yaml

- docs/deployment/intro.md
The redocly CLI command prefix has been updated from openapi to redocly so this documentation needs to be updated to reflect that update.
> docs: updates the redocly cli command prefix from openapi to redocly

- docs/redoc-vendor-extensions.md
We had some broken links reported by our link checker. I reviewed and made other link updates here.
- Found during an internal build
- none
- none
(no code changed)
> docs: fix and update links in redoc-vendor-extensions

- README.md
A README update. We don't use `redoc-cli` any more - Redocly CLI is mentioned in the readme already, so this PR removes the old tool. Also minor tidying up to remove a config option that can't be used, and link to some of the new CLI linting docs.
> docs: Remove Redoc CLI and a non-existent config option

- CHANGELOG.md
- package-lock.json
- package.json
release Redoc v 2.1.0. changes you can see in CHANGELOG file
> chore: v2.1.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/utils/openapi.ts
Crash after 2.1 release due to wrong conversion to string.
Resolves https://github.com/Redocly/redoc/issues/2385
> hotfix: fix crash after 2.1 release

- src/components/SecurityRequirement/OAuthFlow.tsx
Represent refreshToken URL in a similar fashion like Token URL is styled, for consistency in rendering.
When an OAuth security scheme definition is rendered the refreshToken URL is presented as plain text, but it should be a (non-clickable) URL, rendered via `<code>` tag, as the tokenURL is rendered.
One line of template is changed
the wrong rendering:
better rendering:
> Style RefreshToken URL as <code> in the OAuthFlow

- CHANGELOG.md
- package-lock.json
- package.json
release Redoc v2.1.2:
- react18 cli integration
- style RefreshToken URL as `<code>` in the authorization section
> chore: v2.1.2

- demo/ComboBox.tsx
- src/common-elements/schema.ts
- src/components/Schema/OneOfSchema.tsx
- src/components/StickySidebar/StickyResponsiveSidebar.tsx
Following this [fix](https://github.com/Redocly/redoc/pull/2404) I found a few more cases where boolean props are being passed to the DOM. This MR makes them transient as well.
Tested locally with different API descriptions.
> fix: more cases for react18 and cli integration

- src/components/Fields/FieldDetails.tsx
- src/components/__tests__/FieldDetails.test.tsx
- src/components/__tests__/__snapshots__/FieldDetails.test.tsx.snap
When request body has default value as object we display `[object Object]`. 
fixes: https://github.com/Redocly/redoc/issues/2423
_Before_
_After_
> fix: default value as object in request body

- src/components/Fields/ArrayItemDetails.tsx
- src/components/__tests__/FieldDetails.test.tsx
- src/components/__tests__/__snapshots__/FieldDetails.test.tsx.snap
we do not display `pattern` in items with strings.
fixes: https://github.com/Redocly/redoc/issues/2358
_Before_
_After_
> fix: display string pattern in array items

- CHANGELOG.md
- package-lock.json
- package.json
release Redoc v2.1.3:
- fix: default value as object in request body
- fix: display string pattern in array items
- fix: hideRequestPayloadSample
- fix: more cases for react18 and cli integration
> chore: v2.1.3

- README.md
Just proposing our Redoc-based OpenAPI reference for the README's Showcase section.
> Add Quaderno API to README's Showcase section

- docs/deployment/cli.md
Tiny link fix! In the context of the Redoc docs, the link checker can't check links that point to the locations in the wider marketing site. The link checker in that project caught the error, but it must be fixed here.
broken build (Redocly users only) https://github.com/Redocly/marketing-site-portal/actions/runs/7712790410/job/21021123579?pr=1190
> docs: Fix a link that couldn't be checked as it reaches outside the Redoc project

- package-lock.json
- package.json
- update cypress to prevent falling e2e test. 
- update browserslist-db for reduce warning inside e2e tests
https://github.com/cypress-io/cypress/issues/28148
https://github.com/Redocly/redoc/actions/runs/8829130233/job/24239496271
> chore: upgrade cypress to fix e2e tests and update-browserslist-db

- src/common-elements/fields.ts
What: ClickablePropertyName styled component doesn't pass the deprecated css to its child `<span class='property-name'>` and because of that property name doesn't get line-through style.
Solved it by adding the missing css code.
-
No tests needed
Before:
After:
> Add deprecated css to clickable property name

- CHANGELOG.md
- package-lock.json
- package.json
release Redoc v2.1.4:
* add deprecated css to clickable property name ([#2526](https://github.com/Redocly/redoc/issues/2526)) ([b0d03d0](https://github.com/Redocly/redoc/commit/b0d03d02069c1508447ddebc2f8a3fffa9b03ce5))
* use h2/h3 for headings instead of h1/h2 for better seo ([#2514](https://github.com/Redocly/redoc/issues/2514)) ([2b72dc0](https://github.com/Redocly/redoc/commit/2b72dc0e90f759a8ee2e47691c844e7f05928a24))
* security vulnerability ([#2445](https://github.com/Redocly/redoc/pull/2445)) ([1f11f5](https://github.com/Redocly/redoc/commit/1f11f597c4f10ddd601db247f5034052b6ca689f))
> chore: v2.1.4

- .github/sync.yml
We don't need to sync any more, since switching to fetching these docs with the remote content feature.
> docs: Remove outdated sync job for docs folder

- CHANGELOG.md
- package-lock.json
- package.json
Release new Redoc version v2.1.5:
* update react to 18 and react-tabs to 6 ([#2547](https://github.com/Redocly/redoc/issues/2547)) ([c664dd0](https://github.com/Redocly/redoc/commit/c664dd0d56571ce799b8eadd081d86a6b2cdefae))
> chore: v2.1.5

- docs/redoc-vendor-extensions.md
update broken link in OSS Redoc docs
https://github.com/Redocly/redoc/actions/runs/10618307816/job/29433195630?pr=2576
> docs: update broken link of Openapi Object

- src/services/OpenAPIParser.ts
- src/services/__tests__/__snapshots__/OpenAPIParser.test.ts.snap
- src/services/__tests__/fixtures/oneOfHoist.json
fix a bug when oneOf has siblings and it doesn't render correct
fixes https://github.com/Redocly/redoc/issues/641
fixes https://github.com/Redocly/redoc/issues/743
```yaml
Main:
title: Sale
description: A request to authorize and capture funds.
allOf:
- $ref: '#/components/schemas/Anything1'
- type: object
properties:
d:
type: number
oneOf:
- $ref: '#/components/schemas/Anything2'
- $ref: '#/components/schemas/Anything3'
Anything1:
type: object
properties:
a:
type: string
Anything2:
type: object
properties:
b:
type: string
Anything3:
type: object
properties:
c:
type: string
```
```yaml
foo:
type: object
properties:
property1:
type: string
property2:
type: string
property3:
type: string
property4:
type: string
property5:
type: string
property6:
type: string
oneOf:
- required:
- property1
- …
```
> fix: show siblings schema with oneOf

- docs/deployment/cli.md
Older versions of Redoc claimed to be "zero-dependency" but that's not correct for the current version. It was still mentioned in the CLI guide, so this pull request updates those references.
Fixes https://github.com/Redocly/redocly-cli/issues/1731
https://redocly.com/docs/redoc/deployment/cli
> docs: Remove the old zero-dependency claim for Redoc docs

- README.md
- demo/museum.yaml
- demo/openapi.yaml
- docs/redoc-vendor-extensions.md
- e2e/integration/menu.e2e.ts
- src/common-elements/shelfs.tsx
- src/components/Operation/Operation.tsx
- src/components/SideMenu/MenuItem.tsx
- src/components/SideMenu/styled.elements.ts
- src/services/models/Operation.ts
- src/types/open-api.ts
- src/utils/__tests__/__snapshots__/loadAndBundleSpec.test.ts.snap
- src/utils/openapi.ts
Add support x-badges extensions.
fixes: https://github.com/Redocly/redoc/issues/1399
Co-authored-by: @mm-gmbd
Original PR https://github.com/Redocly/redoc/pull/1947
https://redocly.com/docs/realm/author/reference/openapi-extensions/x-badges#openapi-extension-x-badges
> feat: add support x-badges

- CHANGELOG.md
- package-lock.json
- package.json
Release new Redoc version v2.2.0:
* show siblings schema with oneOf ([#2576](https://github.com/Redocly/redoc/issues/2576)) ([60d131b](https://github.com/Redocly/redoc/commit/60d131b0a9dab4710e900323c9ba81160cecf7d8))
* add support x-badges ([#2605](https://github.com/Redocly/redoc/issues/2605)) ([64f1877](https://github.com/Redocly/redoc/commit/64f18779e5fe7e03f25862463cbc5062e85c867c))
> chore: v2.2.0

- docs/quickstart.md
- Changes admonition type from "attention" to "info"
- Eliminates downstream validation errors on admonition
Visually verify in branch preview build
> docs(all): change admonition type to 'info'

- src/common-elements/fields.ts
- src/components/__tests__/__snapshots__/FieldDetails.test.tsx.snap
Hello,
This is a small change that adjusts the styling for patterns being displayed inline for a field.
I've included before and after screenshots using a part of the pet store example.
---
Closes #2196
> feat: update pattern styling (#2196)

- package-lock.json
npm audit fix for preventing feature vulnerabilities
- http-proxy-middleware 2.0.7
- micromatch 4.0.8
> chore: npm audit fix for preventing feature vulnerabilities

- src/components/Fields/ArrayItemDetails.tsx
- src/components/Fields/FieldDetails.tsx
- src/components/__tests__/FieldDetails.test.tsx
- src/components/__tests__/__snapshots__/FieldDetails.test.tsx.snap
fix displaying nested items with type string.
fixes: https://github.com/Redocly/redoc/issues/2516
fixes: https://github.com/Redocly/redoc/issues/2544
https://github.com/Redocly/redoc/issues/2358
```yaml
EndpointIn:
type: object
properties:
uid:
description: Optional unique identifier for the endpoint
type: string
maxLength: 256
minLength: 1
pattern: ^[a-zA-Z0-9\-_.]+$
example: unique-ep-identifier
nullable: true
plain_property:
type: string
pattern: '^[A-Z]+$'
minLength: 1
maxLength: 10
array_items:
type: array
items:
type: string
pattern: '^[A-Z]+$'
minLength: 1
maxLength: 10
macList:
type: array
description: MAC address list
items:
type: string
pattern: ^([0-9a-f]{2}:){5}[0-9a-f]{2}$
macList1:
type: array
description: MAC address list
items:
type: string
pattern: …
```
> fix: displaying nested items with type string

- src/utils/openapi.ts
when you use `showObjectSchemaExamples` and the example is an Object it displays `Example: [object Object]`. That Pr fix it
fixes: https://github.com/Redocly/redoc/issues/2610
> fix: displaying json example when showObjectSchemaExamples enabled

- package-lock.json
- package.json
I moved @cfaester/enzyme-adapter-react-18 to devDependencies instead of dependencies, as I believe this library is intended for testing purposes.
Additionally, I reviewed the installation section in the library's README.md and noticed it specifies using --save-dev.
https://www.npmjs.com/package/@cfaester/enzyme-adapter-react-18
https://github.com/Redocly/redoc/pull/2547/files
None
> fix: move `@cfaester/enzyme-adapter-react-18` to devDependencies

- CHANGELOG.md
- package-lock.json
- package.json
Release Redoc version 2.3.0:
* displaying json example when showObjectSchemaExamples enabled ([#2635](https://github.com/Redocly/redoc/issues/2635)) ([59ee73f](https://github.com/Redocly/redoc/commit/59ee73fefa8e8edb398940076bdd721fc284caa3))
* displaying nested items with type string ([#2634](https://github.com/Redocly/redoc/issues/2634)) ([85b622f](https://github.com/Redocly/redoc/commit/85b622fc581eb96303aeb85056aef36c74ea9f9d))
* passing inline parameters after support react 18 for response title ([#2640](https://github.com/Redocly/redoc/issues/2640)) ([d614d2d](https://github.com/Redocly/redoc/commit/d614d2d022df8bd1989cb0eaf76d087b52120d36))
* update pattern styling ([#2196](https://github.com/Redocly/redoc/issues/2196)) ([#2600](https://github.com/Redocly/redoc/issues/2600)) …
> chore: v2.3.0

- README.md
- docs/config.md
- docs/index.md
- docs/redoc-vendor-extensions.md
- src/utils/openapi.ts
update documentation options for future major release
https://github.com/Redocly/redoc/pull/2647
> docs: update options for future major release

- .github/workflows/publish.yml
CI/CD pipeline failed https://github.com/Redocly/redoc/actions/runs/13161710543/job/36731860990, so we need to update action upload/download artifact
https://github.com/actions/upload-artifact/releases/tag/v4.0.0
> fix: update version download/upload artifacts in cicd

- CHANGELOG.md
- package-lock.json
- package.json
Release Redoc version 2.4.0:
* Prototype Pollution Vulnerability Affecting redoc <=2.2.0 ([#2638](https://github.com/Redocly/redoc/issues/2638)) ([153ec7a](https://github.com/Redocly/redoc/commit/153ec7a0b7245639f404c0b038b612ae7377c7db))
* unify redoc config ([#2647](https://github.com/Redocly/redoc/issues/2647)) ([53a6afc](https://github.com/Redocly/redoc/commit/53a6afc59624fe4591b0a0f1f20f41c0fbb5f1cf))
* add supporting react 19 in package.json ([#2652](https://github.com/Redocly/redoc/issues/2652)) ([3a74802](https://github.com/Redocly/redoc/commit/3a748022be3a7dc7f98669e1645dd5cda72f1abc))
> chore: v2.4.0
